### ISSUE TITLE
Beltrami doesn't work with Freecad 1.0.2

### ISSUE THREAD

**Issue by nermal007** [Simturb/Beltrami#50]
I get the "all ufuncs must have type numpy.ufunc..." error, which I could solve with upgrading the libraries with 
c:\Program Files\FreeCAD 1.0\bin>.\python.exe -m pip install --upgrade numpy scipy sympy
but after that I get the error "cannot import name compose_quat" 
for this I didn't find any solution 
(tried c:\Program Files\FreeCAD 1.0\bin>.\python.exe -m pip install --upgrade torchio)
Any ideas or hints for getting Beltrami to work with Freecad 1.0.2?

**Comment by Simturb** [comment]
Sorry, no tips for you. On my side, I have 3 computers in dual boot and it works everywhere with windows 10, 11 and Ubuntu 24.04.

**Comment by Simturb** [comment]
By the way, I installed the last FreeCAD release 1.1.0 and still everything works great. No problem.

**Comment by Simturb** [comment]
Just a comment, I use AppImage.
